
#include "Core.h"
#include "unity.h"
#include "cmock.h"
#include "LED.h"


void test_LED_Init_Should_TestPInONStatus(void)
{
    LPC_GPIO1->FIOSET = 0;
    LPC_GPIO1->FIOCLR = 0;
    LPC_GPIO1->FIODIR = 0;
    LPC_PINCON->PINSEL3  = 0xFFFFFFFF;
    LPC_PINCON->PINMODE3 = 0xFFFFFFFF;

    LED_Init();

    TEST_ASSERT_EQUAL_HEX(0x00B40000, LPC_GPIO1->FIOSET);
    TEST_ASSERT_EQUAL_HEX(0x00B40000, LPC_GPIO1->FIODIR);
    TEST_ASSERT_EQUAL_HEX(0xFFFF30CF, LPC_PINCON->PINSEL3);
    TEST_ASSERT_EQUAL_HEX(0xFFFF30CF, LPC_PINCON->PINMODE3);
}